#Option 1: for cloud subscription
#FROM ${SERVER_NAME}.jfrog.io/${VIRTUAL_REPO_NAME}/ubuntu:16.04
#Option 2: for Self-Hosted subscription. Remove the above cloud command and use the below command
FROM $http://192.168.1.235:8082/$docker-quickstart/ubuntu:16.04
CMD printf "CONGRATULATIONS!!! You have just set up your first Docker repository with the new JFrog Platform!"
